### ISSUE TITLE
What am I missing? (subscribe_to_orderbook)

### ISSUE THREAD

**Issue by ArturoJ** [slazarov/python-bittrex-websocket-aio#8]
> bittrex_websocket.websocket_client - INFO - Establishing connection to Bittrex through https://beta.bittrex.com/signalr.
    ws.subscribe_to_orderbook(tickers)
AttributeError: 'MySocket' object has no attribute 'subscribe_to_orderbook
bittrex_websocket.websocket_client - INFO - cfscrape detected, using it to bypass Cloudflare.'

Because this happens, the record_trades and ticket_updates go correctly.

**Comment by slazarov** [comment]
Version >=1.x was rewritten completely and all methods were changed to fully cover the official bittrex docs. Please check the readme. Order book subscription is going to be reimplemented soon. You can downgrade to versions before 1.x so that you can use subscribe to order book until it’s implemented.

**Comment by ArturoJ** [comment]
Perfect, thanks for your efforts.

**Comment by slazarov** [comment]
Much appreciated.
  

  
  

  
  
>
